// Writes firestore.rules from firestore.rules.template, filling in the admin
// emails from ADMIN_EMAILS (comma-separated) in .env.local or the environment.
// firestore.rules is git-ignored so the emails stay out of the public repo.
import { existsSync, readFileSync, writeFileSync } from "node:fs";

export function readAdminEmails() {
  let raw = process.env.ADMIN_EMAILS ?? "";
  if (!raw && existsSync(".env.local")) {
    const m = /^ADMIN_EMAILS=(.*)$/m.exec(readFileSync(".env.local", "utf8"));
    raw = m ? m[1] : "";
  }
  return [...new Set(raw.split(",").map((e) => e.trim().replace(/^["']|["']$/g, "").toLowerCase()).filter(Boolean))];
}

export function buildRules(emails) {
  const bad = emails.filter((e) => !/^[^\s@,'"]+@[^\s@,'"]+\.[^\s@,'"]+$/.test(e) || e === "you@example.com");
  if (emails.length === 0 || bad.length) {
    console.error(
      bad.length
        ? `ADMIN_EMAILS has a placeholder or invalid address: ${bad.join(", ")}`
        : "ADMIN_EMAILS is empty. Run: npm run set-admin -- first@example.com second@example.com",
    );
    process.exit(1);
  }
  const template = readFileSync("firestore.rules.template", "utf8");
  const marker = "in [__ADMIN_EMAILS__]";
  if (template.split(marker).length !== 2) {
    console.error(`firestore.rules.template must contain "${marker}" exactly once.`);
    process.exit(1);
  }
  const header = "// GENERATED by scripts/build-rules.mjs from firestore.rules.template — do not edit.\n";
  writeFileSync("firestore.rules", header + template.replace(marker, `in [${emails.map((e) => `'${e}'`).join(", ")}]`));
  console.log(`Wrote firestore.rules for: ${emails.join(", ")}`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  buildRules(readAdminEmails());
}
